### ISSUE TITLE
Add 2FA support

### ISSUE THREAD

**Issue by mnlbox** [platyplus/authentication-server#1]
Hi man,
I want to change this boilerplate login method to 2FA based login.
I see that you are using passport.js now and find this for passport.js:
http://www.passportjs.org/packages/passport-2fa-totp/

Can you guide me to implement this and add this feature to your boilerplate?

I need to implement 2FA based login with send 2FA code through a SMS webhook.

**Comment by plmercereau** [comment]
Thanks @mnlbox for your message.
I have to admit this feature is not a top priority for me, but any contribution is welcome. The use case that I am working on is authentication in a LAN with poor internet connectivity. 2FA, especially the link that you shared, does rely on connectivity - except in considering putting a GSM modem to the local server in order to send SMS... I am not there yet...
For your information, I kind of liked the approach of [DevSpeak](https://github.com/DevSpeak/hasura-simple-auth) in exposing auth graphql resolvers while connecting to the core hasura resolvers to get user information...
I then reshaped it into a [role-based JWT microservice](https://github.com/platyplus/platyplus/blob/master/services/authentication/index.js). It works pretty well to far.

**Comment by mnlbox** [comment]
@plmercereau I like your approach that based on Passport.js because it's very flexible to modify authentication approach to each of strategies. Can you provide some document or example about how we can extend this with other Passport.js strategies?
I think it's very useful If we can modify strategy based on needs.

**Comment by plmercereau** [comment]
To be honest I dont't know passport that much but I took most of the code and inspiration from this [original boilerplate](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates/auth-webhooks/passport-js). I then adapted it to JWT instead of webhooks, and to retrieve not only user credentials but also user roles...
I would compare the two boilterplates so you can understand by proxy how passport works in that case, but am not more experienced in passport than those few lines of code.
Sorry!
