### ISSUE TITLE
Use Apollo Client for data storage

### ISSUE THREAD

**Issue by rorhug** [platyplus/authentication-server#21]
Hey, thanks for this work!

I have a few questions:

1. This auth service connects to the same DB as hasura and uses the same user table, correct?
2. If the above is true, then how would one manage the migrations and metadata of hasura if knex is also doing the same?
3. Would it make sense to create all the models this service uses in Hasura and use apollo client to access them using gql using the `HASURA_GRAPHQL_ADMIN_SECRET`?

**Comment by plmercereau** [comment]
Hello Rory, and thanks for your comments.
Yes, the idea is to use the same database as Hasura although it is not mandatory.
I fully agree with your two last points. In that sense this repo is quite incomplete, but is however less opinionated and could also be used for non-hasura use cases. That being said, there is indeed a potential problem in the conflicting mutation systems.

I already re-wrote this "microservice" that goes in the same sense as your comments: I removed any direct access to Postgres (Knex) and connect to Hasura through GraphQL (although I used the prisma client rather than Apollo - not sure if this was the right choice).

The problem that I see now is that I registered the authentication service as a remote schema in the initial migrations, but the remove schema need Hasura to work. What I do is that I start the auth service first, so Hasura can load the remote schema. But it implies the authentication service should remain idle and  shoud not try to perform any operation that requires the hasura backend to be on.

[Here is the "new" service that I coded since](https://github.com/platyplus/platyplus/tree/master/backend/authentication-service). It is part of a monorepo as I started reusing bits and pieces of code, so I packaged it a little.
I am sorry the documentation is almost non-existent, but will hopefully work on it in the upcoming weeks.

The main features I would like to work on is to put some clarity on the roles management, and also to find a way to implement some kind of a rotating jwk so the private/public key is regularly renewed.

I will be very pleased to get some help of any sort, or even comments and suggestions.

Best

**Comment by rorhug** [comment]
Thanks for your detailed reply, Pilou.

I understand now why you wanted to keep it this project unopinionated from hasura!

As with many projects, it's definitely hard to find/build a *one-size-fits-all* solution to authentication. The service I'm building is to be passwordless/sms. I'm going to use passport [passwordless strategy](https://github.com/florianheinemann/passwordless).

Your insight with regards using remote schemas is useful. I wasn't originally thinking of calling login/signup over graphql. I was more concerned about the auth service using graphql to read the DB.

I'm going to use this and your "new" service as inspiration to build the auth service for my product. When I have something working I will reply with my successes / failures ! :)
